name: conectados 
description: "A new Flutter project." 
publish_to: 'none' 
version: 0.1.0 

environment: 
  sdk: '>=3.8.0-278.1.beta <4.0.0' 

dependencies: 
  flutter: 
    sdk: flutter 
  permission_handler: ^12.0.0+1 
  flutter_blue_plus: ^1.5.2 
  awesome_notifications: ^0.10.1
  notification_listener_service: ^0.3.4 
  shared_preferences: ^2.0.15 
  installed_apps: ^1.3.1
  flutter_background_service: ^5.1.0 

dev_dependencies: 
  flutter_test: 
    sdk: flutter 
  flutter_lints: ^5.0.0 

flutter: 
  uses-material-design: true
