// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF7V1MbdIbZprsPxWc9bNWKTgPM1i72hQ',
    appId: '1:484413962708:web:a6724b91b9feafc3ff7e41',
    messagingSenderId: '484413962708',
    projectId: 'conectados-55fe3',
    authDomain: 'conectados-55fe3.firebaseapp.com',
    storageBucket: 'conectados-55fe3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-f5mXTX0O3NfJOgd03eF8PzCdB3N4MCg',
    appId: '1:484413962708:android:84d90482a785703fff7e41',
    messagingSenderId: '484413962708',
    projectId: 'conectados-55fe3',
    storageBucket: 'conectados-55fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXEVnHrycaEUAHe1g77xYekNrmOt4FBoY',
    appId: '1:484413962708:ios:e8e0bee004ad9fa5ff7e41',
    messagingSenderId: '484413962708',
    projectId: 'conectados-55fe3',
    storageBucket: 'conectados-55fe3.firebasestorage.app',
    iosBundleId: 'com.example.conectados',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXEVnHrycaEUAHe1g77xYekNrmOt4FBoY',
    appId: '1:484413962708:ios:e8e0bee004ad9fa5ff7e41',
    messagingSenderId: '484413962708',
    projectId: 'conectados-55fe3',
    storageBucket: 'conectados-55fe3.firebasestorage.app',
    iosBundleId: 'com.example.conectados',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF7V1MbdIbZprsPxWc9bNWKTgPM1i72hQ',
    appId: '1:484413962708:web:5fba2b382b64f1dfff7e41',
    messagingSenderId: '484413962708',
    projectId: 'conectados-55fe3',
    authDomain: 'conectados-55fe3.firebaseapp.com',
    storageBucket: 'conectados-55fe3.firebasestorage.app',
  );
}
